version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: translite/buddy:${TAG}
    restart: "unless-stopped"
    volumes:
      - "./src:/usr/local/etc/goliatho"
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - "redis"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  redis:
    image: "redis"
    network_mode: "host"
    entrypoint: "redis-server /usr/local/etc/redis/redis.conf"
    restart: "unless-stopped"
    volumes:
      - "./redis:/usr/local/etc/redis"
  #Nginx Service

  # webserver:
  #   image: "nginx:alpine"
  #   container_name: "budyclubApi"
  #   restart: "unless-stopped"
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - "./nginx/conf/:/etc/nginx/conf.d/:ro"
  #     - "./certbot/www:/var/www/certbot/:ro"
  #     - "./certbot/conf/:/etc/nginx/ssl/:ro"
  #   depends_on:
  #     - "api"
  #   network_mode: "host"

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./web-root/:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d/:ro
      - certbot-etc:/etc/letsencrypt/:ro
      - certbot-var:/var/lib/letsencrypt/:ro
    depends_on:
      - api
    network_mode: host

  # certbot:
  #   image: "certbot/certbot:latest"
  #   volumes:
  #     - "./certbot/www/:/var/www/certbot/:rw"
  #     - "./certbot/conf/:/etc/letsencrypt/:rw"
  #   depends_on:
  #     - "webserver"
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email biz.john@yahoo.com --agree-tos --no-eff-email --staging -d budyclub.com -d www.budyclub.com
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt/:rw
      - certbot-var:/var/lib/letsencrypt/:rw
      - ./web-root/:/var/www/html
    depends_on:
      - webserver
    command: certonly -v --webroot --webroot-path=/var/www/html --email biz.john@yahoo.com --agree-tos --no-eff-email --staging -d budyclub.com -d www.budyclub.com

volumes:
  certbot-etc:
  certbot-var:

# networks:
#   budyclub:
#     driver: "host"


# reference
# https://mindsers.blog/post/https-using-nginx-certbot-docker/