version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    volumes:
      - "./lofi:/mediasoup-src"
    ports:
      - "3008:3008"
      - "${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}:${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}/udp"
      - "${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}:${MEDIASOUP_MIN_PORT}-${MEDIASOUP_MAX_PORT}/tcp"
    depends_on:
      - "db"
      - "adminer"
    links:
      - "db"
    networks:
      - "budyclub"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    environment:
      # NODE_ENV: 'production'
      # DOCKER: 'true'
      DATABASE_URL: "${DATABASE_URL}"
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: "always"
    volumes:
      - "./db-postgresql-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    networks:
      - "budyclub"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: '3'
  adminer:
    image: "adminer"
    restart: "always"
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  #Nginx Service
  webserver:
    image: "nginx:alpine"
    container_name: "budyclubApi"
    restart: "unless-stopped"
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "budyclub"
networks:
  budyclub:
    driver: "bridge"